import "@/styles/global.css";
import Navbar from "@/components/shared-components/navbar-components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className="relative h-full min-h-screen font-theme-manrope overflow-x-hidden overflow-y-auto !m-0 !p-0">
        <main className="relative w-full h-full min-h-screen !m-0 !p-0">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
